# 無効にするルール
disabled_rules:
- trailing_whitespace # 余分に改行がある方が視認性が上がる為、無効
- type_name # クラス名は長くして情報を詰めておく必要もある為、無効
- force_try # realm用

# 一行の文字列制限を100文字から300文字に変更
line_length: 300

excluded: # Lint対象から外すファイルのあるパスを記述
- Pods

# クラスの行数
type_body_length:
- 200 # warning
- 400 # error

# 変数名の最大文字数
variable_name_max_length:
- 60 # warning
- 80 # error

# 変数名の最小文字数
variable_name_min_length:
- 1 # warning
- 0 # error

# 関数の長さ
function_body_length:
- 100 # warning
- 200 # error

# Lint対象から除外するパス
excluded:
- Carthage
- Pods
- MyLibraryDemoTests
